### ISSUE TITLE
Include total number of structures in API response

### ISSUE THREAD

**Issue by amanahuja** [eGUIDE/eguide-consumption-api#3]
Based on a user feedback session with a beta user. 

User requested: 
_"in the API response include a total number of structure that the model has found."_

Notes: 
- Total number of structures is just the sum of count of structures in each class. But this was not clear to the user
- An easy thing to include in the JSON response under "data_summary", and will provide a sanity check for users. Seems like a good idea.

**Comment by mugyenyij** [comment]
The total number of structures is located in the data summary section of the data dictionary

```   
 "data_summary": {
        "classA_pooled_prob_mean": 0.08,
        "classA_pooled_prob_std_dev": 0.58,
        "classA_total_count": 12,
        "classB_pooled_prob_mean": 0.65,
        "classB_pooled_prob_std_dev": 0.09,
        "classB_total_count": 24
```

**Comment by amanahuja** [comment]
A user provided feedback by Email and referenced this issue: 

> How many total structures are in that area (i.e. to calculate the proportion of Class A and/or Class B structures of the total)?

**Comment by amanahuja** [comment]
> The total number of structures is located in the data summary section of the data dictionary

No, we are talking about the total number of structures in all classes. This is not yet provided.

**Comment by mugyenyij** [comment]
`Total structure count` added to data dictionary
```
 "data_summary": {
        "classA_pooled_prob_mean": 0.08,
        "classA_pooled_prob_std_dev": 0.58,
        "classA_total_count": 12,
        "classB_pooled_prob_mean": 0.65,
        "classB_pooled_prob_std_dev": 0.09,
        "classB_total_count": 24
        "total_structure_count": 36
```
