### ISSUE TITLE
Model interpretation: Irregular AOI mapped onto a rectangular grid

### ISSUE THREAD

**Issue by amanahuja** [eGUIDE/eguide-consumption-api#7]
> If the AOI is an irregular polygon, does the model take all the building footprints within that AOI into account? Or is the calculation on the back-end still based on the 250m grid?

**Comment by mugyenyij** [comment]
The calculation on the back-end is still based on the 250m grid. All the building footprints are aggregated into 250m, 500m and 1000m resolutions beforehand and then added to a database.  User queries are then made against these grid sizes (250m is the default grid size). 
 
If the user provides an irregular polygon as shown in the illustration below, the response with include all cell grids that are contained within the polygon and that intersect with the polygon at any point. 

![image](https://user-images.githubusercontent.com/44571041/93188493-4fae9d80-f741-11ea-9cc0-44c002fd9669.png)

**Comment by amanahuja** [comment]
@Joel in the example above, is the number of cells returned 15? From visual inspection, only the cell on the bottom right is not included. Maybe you can indicate which cells are returned in the diagram itself??

**Comment by mugyenyij** [comment]
Visual inspection with labels for grid cells that are included


![image](https://user-images.githubusercontent.com/44571041/93188020-c4350c80-f740-11ea-9789-2e538314e52e.png)
